# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 17:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0003_auto_20160604_2312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breaking',
            old_name='title',
            new_name='text',
        ),
        migrations.AddField(
            model_name='breaking',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='breaking',
            name='editor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
