# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 20:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20160605_0131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breaking',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='card',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='heading',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='slides',
            name='editor',
        ),
    ]
