# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20160605_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='image',
            field=models.ImageField(default='', upload_to='static/images/products'),
            preserve_default=False,
        ),
    ]
