# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_card_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.ImageField(upload_to='static/uploads/'),
        ),
    ]
