# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20160605_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.TextField()),
                ('image', models.ImageField(upload_to='slide/')),
            ],
        ),
        migrations.DeleteModel(
            name='Slides',
        ),
        migrations.RemoveField(
            model_name='card',
            name='image_name',
        ),
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.ImageField(upload_to='card/'),
        ),
        migrations.AlterField(
            model_name='card',
            name='text',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='card',
            name='title',
            field=models.TextField(),
        ),
    ]
