# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20160606_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Slide',
        ),
        migrations.AddField(
            model_name='card',
            name='image_name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='card',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
