# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-08 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_auto_20160606_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.TextField()),
                ('image', models.ImageField(upload_to='card/')),
            ],
        ),
        migrations.DeleteModel(
            name='Slides',
        ),
        migrations.RemoveField(
            model_name='card',
            name='image_name',
        ),
    ]
