# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-08 13:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_auto_20160608_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breaking',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='card',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='heading',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='created_date',
        ),
    ]
