# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-11 07:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_auto_20160608_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='section',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='news.Heading'),
            preserve_default=False,
        ),
    ]
