# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 19:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0019_card_heading'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Heading',
            new_name='Section',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='heading',
            new_name='Section',
        ),
    ]
