# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 19:56
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0020_auto_20160616_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='content',
            field=tinymce.models.HTMLField(default=''),
            preserve_default=False,
        ),
    ]
