# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 20:15
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0021_section_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='content',
        ),
        migrations.AlterField(
            model_name='breaking',
            name='text',
            field=tinymce.models.HTMLField(max_length=100),
        ),
        migrations.AlterField(
            model_name='card',
            name='intro_text',
            field=tinymce.models.HTMLField(max_length=200),
        ),
        migrations.AlterField(
            model_name='card',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='card',
            name='title',
            field=tinymce.models.HTMLField(max_length=200),
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=tinymce.models.HTMLField(max_length=200),
        ),
        migrations.AlterField(
            model_name='slide',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
    ]
