# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 03:55
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0022_auto_20160616_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='content',
            field=tinymce.models.HTMLField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='breaking',
            name='text',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='card',
            name='intro_text',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='card',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
