# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 05:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0023_auto_20160616_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='content',
        ),
    ]
