# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 16:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0025_remove_breaking_priority'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Breaking',
        ),
        migrations.RemoveField(
            model_name='card',
            name='Section',
        ),
        migrations.DeleteModel(
            name='Slide',
        ),
        migrations.DeleteModel(
            name='Card',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
