# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 18:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0028_auto_20160627_0004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breaking',
            old_name='date',
            new_name='publish',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='date',
            new_name='publish',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='date',
            new_name='publish',
        ),
        migrations.RenameField(
            model_name='slide',
            old_name='date',
            new_name='publish',
        ),
        migrations.RenameField(
            model_name='top_5',
            old_name='date',
            new_name='publish',
        ),
    ]
