# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0033_auto_20160629_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='Section',
            new_name='section',
        ),
        migrations.AlterField(
            model_name='card',
            name='top',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Top - 1', 'Top - 1'), ('Top - 2', 'Top - 2'), ('Top - 3', 'Top - 3'), ('Top - 4', 'Top - 4'), ('Top - 5', 'Top - 5'), ('Top - 6', 'Top - 6')], max_length=50),
        ),
    ]
