# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-15 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0034_auto_20160705_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='url',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
