# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-15 09:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0036_theme'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Theme',
            new_name='Basic_configuration',
        ),
    ]
