# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-15 09:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0037_auto_20160815_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basic_configuration',
            name='breaking_background',
        ),
        migrations.RemoveField(
            model_name='basic_configuration',
            name='breaking_font',
        ),
        migrations.RemoveField(
            model_name='basic_configuration',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='basic_configuration',
            name='google_plus',
        ),
        migrations.RemoveField(
            model_name='basic_configuration',
            name='header_background',
        ),
        migrations.RemoveField(
            model_name='basic_configuration',
            name='header_text',
        ),
        migrations.RemoveField(
            model_name='basic_configuration',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='basic_configuration',
            name='search_heading',
        ),
        migrations.RemoveField(
            model_name='basic_configuration',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='basic_configuration',
            name='website_background',
        ),
        migrations.RemoveField(
            model_name='basic_configuration',
            name='website_heading',
        ),
        migrations.RemoveField(
            model_name='basic_configuration',
            name='youtube',
        ),
    ]
