# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-15 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0039_auto_20160815_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='basic_configuration',
            name='theme_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
