# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-15 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0040_basic_configuration_theme_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='basic_configuration',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Deactive', 'Deactive')], default='', max_length=20),
            preserve_default=False,
        ),
    ]
