# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-15 11:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0042_smallsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='smallsection',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='smallsection',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Deactive', 'Deactive')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smallsection',
            name='title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
