# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-15 11:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0046_auto_20160815_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(default='', upload_to='advertisement/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertisement',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertisement',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Deactive', 'Deactive')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basicconfiguration',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
