# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-16 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0047_auto_20160815_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='url',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
